Repository KobayaClanguage/find-the-object-game-v2, pull requests merged in 2025-04, with the labels that each got.

#49 Issue/31
  package-lock.json
  package.json
Labels: Bug, High Priority

#42 Issue/33
  CONTRIBUTING.md
Labels: Doc, Under Review

#39 Issue37 : パスワード変更完了画面実装
  src/app/game/settings/account/change/password/complete/page.tsx
Labels: FrontEnd, High Priority, Under Review

#41 Issue30
  src/app/game/settings/account/delete/page.tsx
Labels: FrontEnd, High Priority, Under Review

#43 Issue40
  src/app/game/settings/account/delete/complete/page.tsx
Labels: FrontEnd, High Priority, Under Review

#45 Issue44: パスワードリセット完了画面
  src/app/auth/reset/password/complete/page.tsx
Labels: FrontEnd, High Priority, Under Review

#46 Issue29: ログアウト画面実装
  src/app/game/settings/account/logout/page.tsx
Labels: FrontEnd, High Priority, Under Review

#53 Issue52 : パスワードリセット用URL(マジックリンク)送信完了画面
  src/app/auth/reset/password/send/page.tsx
Labels: FrontEnd, High Priority, Under Review

#51 Issue50: パスワード再設定用URL送信画面の実装
  src/app/auth/reset/password/page.tsx
Labels: FrontEnd, High Priority, Under Review

#48 Issue47 : パスワード再設定画面実装
  src/app/auth/reset/password/register/page.tsx
Labels: FrontEnd, High Priority, Under Review

#57 Issue27: メールアドレス変更画面(/game/settings/account/change/email)
  src/app/game/settings/account/change/email/page.tsx
Labels: FrontEnd, High Priority, In Progress

#60 issue17:設定画面
  src/app/game/settings/page.tsx
Labels: FrontEnd, High Priority, In Progress

#61 Issue/36
  src/app/game/settings/account/change/email/send/page.tsx
Labels: FrontEnd, High Priority, Under Review

#62 メールアドレス変更完了画面を実装した
  src/app/game/settings/account/change/email/complete/page.tsx
Labels: FrontEnd, High Priority, Under Review

#74 Issue/63
  package-lock.json
  package.json
  src/app/auth/login/page.tsx
  src/features/auth/auth.ts
  src/firebase/config.ts
Labels: BackEnd, High Priority, In Progress

#75 新規アカウント登録機能を実装した(issue/65)
  src/app/auth/register/page.tsx
  src/features/auth/auth.ts
  src/firebase/config.ts
Labels: BackEnd, High Priority, In Progress

#77 Issue/76
  src/app/game/scan/page.tsx
  src/app/game/settings/account/logout/complete/page.tsx
  src/app/game/settings/info/aboutUs/page.tsx
  src/app/game/settings/info/howToPlay/page.tsx
  src/app/game/settings/info/termsOfUse/page.tsx
Labels: Bug
