Repository KobayaClanguage/find-the-object-game-v2, pull requests merged in 2025-05, with the labels that each got.

#81 issue/80 (game/settings/account/delete)
  src/app/game/settings/account/delete/page.tsx
Labels: FrontEnd

#82 Issue/66: アカウント削除機能の実装(game/settings/account/delete)
  src/app/game/settings/account/delete/page.tsx
  src/features/auth/auth.ts
Labels: BackEnd

#85 Issue84 : フォーマッターを導入しました
  .gitattributes
  .husky/pre-commit
  .vscode/settings.json
  biome.json
  components.json
  eslint.config.mjs
  package.json
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
  src/app/game/settings/account/change/email/complete/page.tsx
  src/app/game/settings/account/change/email/page.tsx
  src/app/game/settings/account/change/email/send/page.tsx
  src/app/game/settings/account/change/password/page.tsx
  src/app/game/settings/account/delete/page.tsx
  src/app/game/settings/account/logout/page.tsx
  src/app/game/settings/page.tsx
  src/app/game/stamp/[stampId]/page.tsx
  src/app/globals.css
  src/components/ui/button.tsx
  src/components/ui/card.tsx
  src/components/ui/input.tsx
  src/components/ui/label.tsx
  src/features/auth/auth.ts
  src/lib/utils.ts
  tailwind.config.ts
Labels: Low Priority

#87 issue86: 変数名とReactのimportを修正した
  src/app/game/settings/account/delete/page.tsx
  src/features/auth/auth.ts
Labels: BackEnd, Low Priority

#98 Issue/91 & Issue/78 : 二つともログイン画面のリンクURLのミス対応
  src/app/auth/login/page.tsx
  src/app/auth/register/page.tsx
Labels: Bug
