Repository KobayaClanguage/find-the-object-game-v2, pull requests merged in 2025-08, with the labels that each got.

#137 Issue/136 : 遊び方ページに「QRコードがデンソーウェーブの登録商標であることを記載」
  src/app/game/settings/info/howToPlay/page.tsx
Labels: FrontEnd

#139 Issue/138 : トップページを実装
  bun.lock
  package.json
  src/app/page.tsx
Labels: FrontEnd

#141 ログイン前でも見れる利用規約ページのパスを修正した(issue/140)
  package.json
  src/app/auth/register/page.tsx
  src/app/unauth/info/termsOfUse/page.tsx
Labels: Refactoring

#143 Issue/142 : 遊び方ページの内容をコンポーネントに切りだした
  src/app/game/settings/info/howToPlay/page.tsx
  src/features/game/settings/info/howToPlay.tsx
  tailwind.config.ts
Labels: FrontEnd

#145 Issue/144 : 準備中ページの実装
  src/app/page.tsx
  src/app/preparation/page.tsx
Labels: FrontEnd, High Priority
